using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DialougeScript : MonoBehaviour
{

    [Header("All Commands: All commands have the &- prefix\n\\n&-DebugCommand // Makes a debug.log appear\r\n\r\n&-Give-R // Gives the player R material indicated by the next line of the script\r\n&-Give-G // Gives the player G material indicated by the next line of the script\r\n&-Give-B // Gives the player B material indicated by the next line of the script\r\n&-Give-Y // Gives the player B material indicated by the next line of the script\r\n\r\n&-Choice-1 // Creates a choice for the player with one option\r\n&-Choice-2 // Creates a choice for the player with two options\r\n&-Choice-4 // Creates a choice for the player with four options\r\n\r\n&-Warp // Teleports to the line indicated by the next line of the script\r\n\r\n&-Warp-IfWarrior // Teleports to the line indicated by the next line of the script if Warrior, Otherwise skips the next line\r\n&-Warp-IfInventor // Teleports to the line indicated by the next line of the script if Inventor, Otherwise skips the next line\r\n&-Warp-IfBuilder // Teleports to the line indicated by the next line of the script if Builder, Otherwise skips the next line\r\n&-Warp-IfSalvager // Teleports to the line indicated by the next line of the script if Salvager, Otherwise skips the next line\r\n\r\n&-SetRole-Warrior // Makes the player's role Warrior\r\n&-SetRole-Inventor // Makes the player's role Inventor\r\n&-SetRole-Builder // Makes the player's role Builder\r\n&-SetRole-Salvager // Makes the player's role Salvager")]
    //[TextArea(0, 5)]
    //[Tooltip("All Commands: All commands have the &- prefix\r\n\r\n            &-DebugCommand // Makes a debug.log appear\r\n\r\n            &-Give-R // Gives the player R material indicated by the next line of the script\r\n            &-Give-G // Gives the player G material indicated by the next line of the script\r\n            &-Give-B // Gives the player B material indicated by the next line of the script\r\n            &-Give-Y // Gives the player B material indicated by the next line of the script\r\n\r\n            &-Choice-1 // Creates a choice for the player with one option\r\n            &-Choice-2 // Creates a choice for the player with two options\r\n            &-Choice-4 // Creates a choice for the player with four options\r\n\r\n            &-Warp // Teleports to the line indicated by the next line of the script\r\n\r\n            &-Warp-IfWarrior // Teleports to the line indicated by the next line of the script if Warrior, Otherwise skips the next line\r\n            &-Warp-IfInventor // Teleports to the line indicated by the next line of the script if Inventor, Otherwise skips the next line\r\n            &-Warp-IfBuilder // Teleports to the line indicated by the next line of the script if Builder, Otherwise skips the next line\r\n            &-Warp-IfSalvager // Teleports to the line indicated by the next line of the script if Salvager, Otherwise skips the next line\r\n\r\n            &-SetRole-Warrior // Makes the player's role Warrior\r\n            &-SetRole-Inventor // Makes the player's role Inventor\r\n            &-SetRole-Builder // Makes the player's role Builder\r\n            &-SetRole-Salvager // Makes the player's role Salvager")]

    public string[] script;
    
}
